/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.expressswallows.view;

import com.expressswallows.model.restaurant.users.Client;
import com.expressswallows.model.restaurant.Order;
import com.expressswallows.utils.Utils;

import javax.swing.ImageIcon;
import java.util.ResourceBundle;

/**
 *
 * @author shahi
 */
public class FormDrinksMenu extends javax.swing.JFrame {
    Order order;
    Client client;
    ImageIcon drink = new ImageIcon("FoodDeliverySystem/drinks.jpg");
    private final double SMALL = 3.99;
    private final double MEDIUM = 4.99;
    private final double LARGE = 5.49;
    private double currentPrice = 0;
    /**
     * Creates new form frmDrinksMenu
     */
    public FormDrinksMenu(Client client, Order order) {
        initComponents();
        this.client = client;
        this.order = order;
        drinkImg.setText("");
        drinkImg.setIcon(drink);

        update();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        langBtn = new javax.swing.JButton();
        drinksMenuLbl = new javax.swing.JLabel();
        drinkImg = new javax.swing.JLabel();
        sizeLbl = new javax.swing.JLabel();
        typesLbl = new javax.swing.JLabel();
        orderBtn = new javax.swing.JButton();
        typeBox = new javax.swing.JComboBox<>();
        sizeBox = new javax.swing.JComboBox<>();
        priceLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        langBtn.setText("French");
        langBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langBtnActionPerformed(evt);
            }
        });

        drinksMenuLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        drinksMenuLbl.setText("Drinks Menu");

        drinkImg.setText("jLabel1");

        sizeLbl.setText("Size");

        typesLbl.setText("Types");

        orderBtn.setText("Add to cart");
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });

        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Water", "Coke", "7up" }));
        typeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeBoxActionPerformed(evt);
            }
        });

        sizeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large" }));
        sizeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeBoxActionPerformed(evt);
            }
        });

        priceLbl.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGap(67, 67, 67)
                .addComponent(drinksMenuLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(langBtn)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(drinkImg, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sizeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sizeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(priceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drinksMenuLbl)
                    .addComponent(langBtn)
                    .addComponent(backBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drinkImg, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeLbl)
                    .addComponent(typesLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(priceLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderBtn)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update() {
        ResourceBundle rb = ResourceBundle.getBundle("messages", Utils.currentLocale);
        backBtn.setText(rb.getString("back"));
        langBtn.setText(rb.getString("lang"));
        drinksMenuLbl.setText(rb.getString("drinksmenu"));
        sizeLbl.setText(rb.getString("size"));

        String priceText = String.format("%.2f", currentPrice);
        if (Utils.currentLocale.getLanguage().equals("en")) {
            // In English, put $ before the price
            priceLbl.setText(rb.getString("price") + " $" + priceText);  // Add "Price:" and the currency symbol
        } else if (Utils.currentLocale.getLanguage().equals("fr")) {
            // In French, put € after the price
            priceLbl.setText(rb.getString("price") + " " + priceText + "$");  // Add "Prix:" and the currency symbol
        }


        orderBtn.setText(rb.getString("addtocart"));

        typeBox.removeItemAt(0);
        typeBox.insertItemAt(rb.getString("water"),0);

        sizeBox.removeAllItems();

        sizeBox.addItem(rb.getString("small"));
        sizeBox.addItem(rb.getString("medium"));
        sizeBox.addItem(rb.getString("large"));
    }

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new FormClientMainMenu(client, order).setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void langBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langBtnActionPerformed
        int selectedSize = sizeBox.getSelectedIndex();
        int selectedType = typeBox.getSelectedIndex();
        Utils.switchLanguage();
        update();
        sizeBox.setSelectedIndex(selectedSize);
        typeBox.setSelectedIndex(selectedType);
    }//GEN-LAST:event_langBtnActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderBtnActionPerformed

    private void sizeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeBoxActionPerformed
        int selectedSize = sizeBox.getSelectedIndex();

        switch (selectedSize) {
            case 0 -> currentPrice = SMALL;  // Small price
            case 1 -> currentPrice = MEDIUM; // Medium price
            case 2 -> currentPrice = LARGE;  // Large price
        }

        String priceText = String.format("%.2f", currentPrice);
        if (Utils.currentLocale.getLanguage().equals("en")) {
            // In English, put $ before the price
            priceLbl.setText("Price: $" + priceText);
        } else if (Utils.currentLocale.getLanguage().equals("fr")) {
            // In French, put € after the price
            priceLbl.setText("Prix: " + priceText + "$");
        }
    }//GEN-LAST:event_sizeBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel drinkImg;
    private javax.swing.JLabel drinksMenuLbl;
    private javax.swing.JButton langBtn;
    private javax.swing.JButton orderBtn;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JComboBox<String> sizeBox;
    private javax.swing.JLabel sizeLbl;
    private javax.swing.JComboBox<String> typeBox;
    private javax.swing.JLabel typesLbl;
    // End of variables declaration//GEN-END:variables
}
